#!/usr/bin/env bash
set -x
set -e

env

# #sudo chown -R $USER /usr/local/rvm
# export PATH=/usr/local/rvm/bin:$PATH
# export rvm_install_on_use_flag=1
# 
# rvm -v
# 
# rvm $1

if [ "1.8.7" != "$1" ]
then
  source use_ruby.sh
  use_ruby $1
fi

gem install bundler --no-rdoc --no-ri

# bundle version
# which bundle
# which rake
# which ruby

time bundle install --path vendor/bundle --without development
time bundle exec rake

echo
echo "Complete"
